import React, { useState, useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import { useAuth } from '../../modules/auth/hooks/useAuth';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { AIContact } from '../types/types';
import { mockContacts } from '../data/contacts';

// Components
import LandingPage from '../../components/LandingPage';
import PricingPage from '../../components/PricingPage';
import SuccessNotice from '../../components/SuccessNotice';
import AuthScreen from '../../modules/auth/components/AuthScreen';
import ChatScreen from '../../modules/chat/components/ChatScreen';
import CallScreen from '../../modules/voice/components/CallScreen';
import OAuthCallback from '../../modules/oauth/components/OAuthCallback';
import { Dashboard, ContactSidebar, SettingsSidebar, SettingsScreen } from '../../modules/ui';

type AppView = 'landing' | 'auth' | 'pricing' | 'dashboard' | 'chat' | 'call' | 'settings';

export default function App() {
  const { user, loading } = useAuth();
  const [contacts, setContacts] = useLocalStorage<AIContact[]>('ai-contacts', mockContacts);
  const [currentView, setCurrentView] = useState<AppView>('landing');
  const [selectedContact, setSelectedContact] = useState<AIContact | null>(null);
  const [showSuccessNotice, setShowSuccessNotice] = useState(false);
  const [successMessage, setSuccessMessage] = useState('');
  const [showPricing, setShowPricing] = useState(false);

  // Check for success parameter in URL (from Stripe redirect)
  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('success') === 'true') {
      setSuccessMessage('🎉 Payment successful! Welcome to your premium plan!');
      setShowSuccessNotice(true);
      // Clean up URL
      window.history.replaceState({}, document.title, window.location.pathname);
    }
  }, []);

  // Redirect logic based on auth state
  useEffect(() => {
    if (loading) return;

    if (!user) {
      if (currentView !== 'landing' && currentView !== 'auth') {
        setCurrentView('landing');
      }
    } else {
      // User is authenticated
      if (currentView === 'landing' || currentView === 'auth') {
        // Check if user just signed up (no subscription plan set or is 'free')
        const userProfile = user.user_metadata;
        const hasSeenPricing = localStorage.getItem('hasSeenPricing');
        
        if (!hasSeenPricing && (!userProfile?.subscription_plan || userProfile.subscription_plan === 'free')) {
          setShowPricing(true);
          localStorage.setItem('hasSeenPricing', 'true');
        } else {
          setCurrentView('dashboard');
        }
      }
    }
  }, [user, loading, currentView]);

  const handleGetStarted = () => {
    setCurrentView('auth');
  };

  const handleAuthSuccess = () => {
    // This will be handled by the useEffect above
  };

  const handleSelectPlan = (planId: string) => {
    // In a real app, this would redirect to Stripe checkout
    // For now, we'll simulate a successful payment
    console.log('Selected plan:', planId);
    
    // Simulate Stripe checkout redirect
    const checkoutUrl = `https://checkout.stripe.com/pay/cs_test_${planId}#fidkdWxOYHwnPyd1blpxYHZxWjA0VGxKNkpqNWJLNGJhNGJKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNKNjNK`;
    
    // Simulate redirect to success page
    setTimeout(() => {
      window.location.href = `${window.location.origin}?success=true`;
    }, 1000);
  };

  const handleSkipToPro = () => {
    setShowPricing(false);
    setCurrentView('dashboard');
  };

  const handleChatClick = (contact: AIContact) => {
    setSelectedContact(contact);
    setCurrentView('chat');
  };

  const handleCallClick = (contact: AIContact) => {
    setSelectedContact(contact);
    setCurrentView('call');
  };

  const handleSettingsClick = (contact?: AIContact) => {
    if (contact) {
      setSelectedContact(contact);
      setCurrentView('settings');
    }
  };

  const handleHomeClick = () => {
    setCurrentView('dashboard');
    setSelectedContact(null);
  };

  const handleCreateAgent = () => {
    // Create a new agent with default values
    const newAgent: AIContact = {
      id: Date.now().toString(),
      name: 'New AI Assistant',
      description: 'A helpful AI assistant ready to be customized',
      initials: 'AI',
      color: '#3b82f6',
      status: 'online',
      lastSeen: 'now',
      voice: 'Puck'
    };
    
    setContacts(prev => [...prev, newAgent]);
    setSelectedContact(newAgent);
    setCurrentView('settings');
  };

  const handleSaveContact = (updatedContact: AIContact) => {
    setContacts(prev => 
      prev.map(contact => 
        contact.id === updatedContact.id ? updatedContact : contact
      )
    );
    setSelectedContact(updatedContact);
    setCurrentView('dashboard');
  };

  const handleNewChatClick = (contact: AIContact) => {
    handleChatClick(contact);
  };

  // Show loading screen
  if (loading) {
    return (
      <div className="h-screen bg-glass-bg flex items-center justify-center">
        <div className="text-white text-xl">Loading...</div>
      </div>
    );
  }

  // Show pricing page if user just signed up
  if (showPricing) {
    return (
      <PricingPage
        onSelectPlan={handleSelectPlan}
        onSkipToPro={handleSkipToPro}
      />
    );
  }

  // Show landing page for non-authenticated users
  if (!user && currentView === 'landing') {
    return <LandingPage onGetStarted={handleGetStarted} />;
  }

  // Show auth screen
  if (!user && currentView === 'auth') {
    return <AuthScreen onAuthSuccess={handleAuthSuccess} />;
  }

  // Main app layout for authenticated users
  return (
    <Router>
      <div className="h-screen bg-glass-bg flex overflow-hidden">
        {/* Success Notice */}
        {showSuccessNotice && (
          <SuccessNotice
            message={successMessage}
            onClose={() => setShowSuccessNotice(false)}
          />
        )}

        <Routes>
          {/* OAuth Callback Route */}
          <Route path="/oauth/callback/:provider" element={<OAuthCallback />} />
          
          {/* Main App Route */}
          <Route path="*" element={
            <>
              {currentView === 'dashboard' ? (
                <Dashboard
                  contacts={contacts}
                  onChatClick={handleChatClick}
                  onCallClick={handleCallClick}
                  onSettingsClick={handleSettingsClick}
                  onNewChatClick={handleNewChatClick}
                  onCreateAgent={handleCreateAgent}
                />
              ) : currentView === 'settings' && selectedContact ? (
                <SettingsScreen
                  contact={selectedContact}
                  onBack={handleHomeClick}
                  onSave={handleSaveContact}
                />
              ) : (
                <>
                  {/* Sidebar */}
                  <div className="w-80 border-r border-slate-700 flex-shrink-0">
                    <ContactSidebar
                      contacts={contacts}
                      onChatClick={handleChatClick}
                      onCallClick={handleCallClick}
                      onSettingsClick={handleSettingsClick}
                      onHomeClick={handleHomeClick}
                      onCreateAgent={handleCreateAgent}
                    />
                  </div>

                  {/* Main Content */}
                  <div className="flex-1 flex">
                    <div className="flex-1">
                      {currentView === 'chat' && selectedContact ? (
                        <ChatScreen
                          contact={selectedContact}
                          onBack={handleHomeClick}
                        />
                      ) : currentView === 'call' && selectedContact ? (
                        <CallScreen
                          contact={selectedContact}
                          onBack={handleHomeClick}
                        />
                      ) : (
                        <div className="h-full flex items-center justify-center bg-glass-bg">
                          <div className="text-center">
                            <div className="text-6xl mb-4">💬</div>
                            <h2 className="text-2xl font-bold text-white mb-2">Welcome to Gather</h2>
                            <p className="text-slate-400">Select a contact to start chatting</p>
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Settings Sidebar */}
                    {(currentView === 'chat' || currentView === 'call') && selectedContact && (
                      <div className="w-80 border-l border-slate-700 flex-shrink-0">
                        <SettingsSidebar
                          contact={selectedContact}
                          onSave={handleSaveContact}
                        />
                      </div>
                    )}
                  </div>
                </>
              )}
            </>
          } />
        </Routes>
      </div>
    </Router>
  );
}